spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12345678

    mvc:
      pathmatch:
        matching-strategy: ANT_PATH_MATCHER

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


    #JPA Settings
    jpa.hibernate.ddl-auto: create

management:
      endpoints:
        web:
          exposure:
            include: "beans, health, metrics"
          base-path: "/management-dashboard"

      endpoint:
        health:
          show-details: always