spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12345678

#JPA Settings
  jpa.hibernate.ddl-auto: create